version: "3.5"

volumes:
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            device: /home/wordpress  # path to your wordpress files
            type: none
            o: bind
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            device: /home/mariadb  # path to your mariadb files
            type: none
            o: bind

networks:
    inception:
        name: inception

services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        image: nginx:42
        ports:
            - "443:443"
        depemds_on:
            - wordpress
        volumes:
            - wordpress:/var/www/html
        networks:
            - inception
        env_file:
            - .env
        restart: always

    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        image: wordpress:42
        depends_on:
            - mariadb
        volumes:
            - wordpress:/var/www/html
        networks:
            - inception
        env_file:
            - .env
        restart: always

    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        image: mariadb:42
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - inception
        env_file:
            - .env
        restart: always
